# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wolfr\PycharmProjects\Maria\designs\AddWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(219, 216)
        Dialog.setMinimumSize(QtCore.QSize(219, 216))
        Dialog.setMaximumSize(QtCore.QSize(400, 400))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 167, 198))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_row = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_row.setFont(font)
        self.lineEdit_row.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_row.setMaxLength(20)
        self.lineEdit_row.setObjectName("lineEdit_row")
        self.verticalLayout.addWidget(self.lineEdit_row)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_column = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_column.setFont(font)
        self.lineEdit_column.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_column.setMaxLength(20)
        self.lineEdit_column.setObjectName("lineEdit_column")
        self.verticalLayout.addWidget(self.lineEdit_column)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_element = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_element.setFont(font)
        self.lineEdit_element.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_element.setMaxLength(20)
        self.lineEdit_element.setObjectName("lineEdit_element")
        self.verticalLayout.addWidget(self.lineEdit_element)
        self.pushButton_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Номер строки:"))
        self.label_2.setText(_translate("Dialog", "Номер столбца:"))
        self.label_3.setText(_translate("Dialog", "Значение элемента:"))
        self.pushButton_add.setText(_translate("Dialog", "Добавить элемент"))
