# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wolfr\PycharmProjects\maria_matrix\designs\DeleteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteWindow(object):
    def setupUi(self, DeleteWindow):
        DeleteWindow.setObjectName("DeleteWindow")
        DeleteWindow.resize(214, 160)
        DeleteWindow.setMinimumSize(QtCore.QSize(151, 160))
        DeleteWindow.setMaximumSize(QtCore.QSize(400, 200))
        self.centralwidget = QtWidgets.QWidget(DeleteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_row = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_row.setFont(font)
        self.lineEdit_row.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_row.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_row.setObjectName("lineEdit_row")
        self.verticalLayout.addWidget(self.lineEdit_row)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_column = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_column.setFont(font)
        self.lineEdit_column.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_column.setObjectName("lineEdit_column")
        self.verticalLayout.addWidget(self.lineEdit_column)
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.verticalLayout.addWidget(self.pushButton_delete)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        DeleteWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteWindow)

    def retranslateUi(self, DeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteWindow.setWindowTitle(_translate("DeleteWindow", "MainWindow"))
        self.label.setText(_translate("DeleteWindow", "Номер строки:"))
        self.label_2.setText(_translate("DeleteWindow", "Номер столбца:"))
        self.pushButton_delete.setText(_translate("DeleteWindow", "Удалить элемент"))
